name: acceptance-stage.yml
on:
  workflow_run:
    workflows:
      - commit-stage.yml
    types:
      - completed
    branches: main

concurrency: acceptance

env:
  OWNER: bechernie
  REGISTRY: ghcr.io
  APP_REPO: order-service
  DEPLOY_REPO: polar-deployment
  VERSION: ${{ github.sha }}

jobs:
  functional:
    name: Functional Acceptance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running functional acceptance tests"
  performace:
    name: Performance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running performance tests"
  security:
    name: Security Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running security tests"
  deliver:
    name: Deliver release candidate to production
    needs:
      - functional
      - performace
      - security
    runs-on: ubuntu-22.04
    steps:
      - name: Deliver application to production
        uses: peter-evans/repository-dispatch@v2
        with:
          token: '${{ secrets.DISPATCH_TOKEN }}'
          repository: '${{ env.OWNER }}/${{ env.DEPLOY_REPO }}'
          event-type: app_delivery
          client-payload: '{
            "app_image": "${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.APP_REPO }}",
            "app_name": "${{ env.APP_REPO }}",
            "app_version": "${{ env.VERSION }}"
          }'